apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kanboard
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - kanboard.aidengrossman.com
    secretName: kanboard
  rules:
  - host: kanboard.aidengrossman.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kanboard
            port:
              number: 80