apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thelounge
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - irc.aidengrossman.com
    secretName: irc
  rules:
  - host: irc.aidengrossman.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: thelounge
            port:
              number: 80

