apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdav
spec:
  selector:
    matchLabels:
      app: webdav
  replicas: 1
  template:
    metadata:
      labels:
        app: webdav
    spec:
      containers:
      - image: docker.io/bytemark/webdav
        env:
          - name: AUTH_TYPE
            value: "Digest"
          - name: USERNAME
            value: "aiden"
          - name: PASSWORD
            value: "qBQ5r&X!g%"
        imagePullPolicy: IfNotPresent
        name: webdav
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /var/lib/dav
            name: webdav-data
      volumes:
        - name: webdav-data
          persistentVolumeClaim:
            claimName: webdav-data
