apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      nodeName: k3s-node2
      containers:
      - name: minecraft
        image: itzg/minecraft-server
        env:
          - name: OPS
            value: hartreefock
          - name: DIFFICULTY
            value: hard
          - name: VERSION
            value: "1.18.1"
          - name: EULA
            value: "TRUE"
          - name: MEMORY
            value: "3G"
        ports:
        - containerPort: 25565
        volumeMounts:
          - mountPath: /data
            name: minecraft-pvc
      volumes:
        - name: minecraft-pvc
          persistentVolumeClaim:
            claimName: minecraft
