apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin-webdav
spec:
  selector:
    matchLabels:
      app: jellyfin-webdav
  replicas: 1
  template:
    metadata:
      labels:
        app: jellyfin-webdav
    spec:
      containers:
      - image: docker.io/bytemark/webdav
        env:
          - name: AUTH_TYPE
            value: "Digest"
          - name: USERNAME
            value: "aiden"
          - name: PASSWORD
            value: "asp.net4.5"
        imagePullPolicy: IfNotPresent
        name: jellyfin-webdav
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /var/lib/dav
            name: jellyfin-data
      volumes:
        - name: jellyfin-data
          persistentVolumeClaim:
            claimName: jellyfin-data
