apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin-webdav
spec:
  selector:
    matchLabels:
      app: jellyfin-webdav
  replicas: 1
  template:
    metadata:
      labels:
        app: jellyfin-webdav
    spec:
      containers:
      - image: docker.io/dgraziotin/nginx-webdav-nononsense
        env:
          - name: WEBDAV_USERNAME
            value: "aiden"
          - name: WEBDAV_PASSWORD
            value: "asp.net4.5"
          - name: TIMEOUTS_S
            value: "1200"
          - name: CLIENT_MAX_BODY_SIZE
            value: "50G"
          - name: PUID
            value: "82"
          - name: GUID
            value: "82"
        imagePullPolicy: IfNotPresent
        name: jellyfin-webdav
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /data
            name: jellyfin-data
      volumes:
        - name: jellyfin-data
          persistentVolumeClaim:
            claimName: jellyfin-data
