apiVersion: apps/v1
kind: Deployment
metadata:
  name: discordirc
spec:
  selector:
    matchLabels:
      app: discordirc
  replicas: 1
  template:
    metadata:
      labels:
        app: discordirc
    spec:
      containers:
      - image: discordirc/discord-irc:latest
        imagePullPolicy: IfNotPresent
        name: discordirc
        volumeMounts:
          - name: config
            mountPath: /config
      volumes:
        - name: config
          configMap:
            name: config
