operator:
  satelliteSet:
    storagePools:
      lvmThinPools:
        - name: hdd
          thinVolume: piraeus-thin
          volumeGroup: hdd
        - name: ssd
          thinVolume: piraeus-thin
          volumeGroup: ssd
